#!/usr/bin/env bash

image="$1"

if [ -z "$image" ] ; then
  me="$(basename "$0")"
  echo "Usage: $me <image>"
  exit 1
fi

exec qemu-system-x86_64 \
     -cpu host \
     -drive file="${image}",index=0,media=disk,if=virtio \
     -net nic,model=virtio \
     -net user,net=10.0.2.0/24 \
     -nographic \
     -vga none \
     -parallel none \
     --enable-kvm
